### PR TITLE
Replace Makefile with invoke

### PR DESCRIPTION
**Pull request by lfdebrux**

### CODE REVIEW

**Comment by gidsg** [comment]
@lfdebrux seems like `make` no longer runs the app as previously, so I think we at least need to update https://github.com/alphagov/digitalmarketplace-runner/blob/b76a22f628946e1c2346d083590baf7ef417f5ab/README.md#instructions

**Comment by lfdebrux** [comment]
> @lfdebrux seems like make no longer runs the app as previously, so I think we at least need to update https://github.com/alphagov/digitalmarketplace-runner/blob/b76a22f628946e1c2346d083590baf7ef417f5ab/README.md#instructions

Done

**Comment by gidsg** [comment]
@lfdebrux not sure if I've missed something but getting the following error when trying to follow the README:
```
$ invoke setup   
entering virtualenv at `venv`
Collecting pip
  Using cached https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-21.0.1
pyenv: pip-sync: command not found

The `pip-sync' command exists in these Python versions:
  3.6.8

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```

**Comment by lfdebrux** [comment]
@gidsg hmm, interesting. Thanks for testing it, I will investigate.

**Comment by gidsg** [comment]
@lfdebrux I am trying `invoke brew` now, in case I am missing any shared dependencies.

**Comment by lfdebrux** [comment]
@gidsg looks like the requirements file for this project is missing `pip-tools`

**Comment by lfdebrux** [comment]
I need to make some changes to dmdevtools...

**Comment by lfdebrux** [comment]
Okay, I've made a bunch of changes to dmdevtools and pushed a commit to bump dmrunner to use the latest version, I think this is ready to go.

**Review by gidsg — APPROVED** [review]
Tried all the commands in the README and this looks good to me 👍 🎉

**Pull request merged**
