### PR TITLE
upgrade to Node 14 LTS

### PR DESCRIPTION
**Pull request by gidsg**
https://trello.com/c/0BmkYFSD/907-3-node-10-is-eol-april-2021-upgrade-node-to-v14

### CODE REVIEW

**Comment by lfdebrux** [comment]
We'll also want to update the README

**Comment by lfdebrux** [comment]
Hmm, `make setup` complains about the wrong version now:

```
setup | Checking Node version ...
setup | * You have Node v14.16.1 installed; you should use lts/fermium
```

The check in https://github.com/alphagov/digitalmarketplace-runner/blob/main/dmrunner/setup.py#L175 isn't very clever :/

**Comment by gidsg** [comment]
> Hmm, make setup complains about the wrong version now:

Good spot @lfdebrux, this should be fixed now in 58d889a.

**Comment by lfdebrux** [comment]
> > Hmm, make setup complains about the wrong version now:
> 
> Good spot @lfdebrux, this should be fixed now in [58d889a](https://github.com/alphagov/digitalmarketplace-runner/commit/58d889a1e85b941d771a1ced9e4c7cb2addbe447).

`make setup` works for me now, although I did have to delete all my node_modules folders with `rm -r digitalmarketplace-*-frontend/node_modules` first

**Review by lfdebrux — APPROVED** [review]

**Pull request merged**
