### PR TITLE
Add `make data` command

### PR DESCRIPTION
**Pull request by samuelhwilliams**
## Summary
Most of the time we won't need to run a full setup, instead we just want
to repopulate postgres and elasticsearch from newer data.

### CODE REVIEW

**Comment by lfdebrux** [comment]
There is one issue with search indexes; if you run make data you will lose indexes for old frameworks, which means old direct_award projects stop working.

**Comment by samuelhwilliams** [comment]
Ah interesting. That's more a side-effect of the updated `settings.yml` than anything else (I think?), which no longer includes g-cloud-9.

You could add that back in, at which point `make data` will also create an index for that and the proble should go away?

**Comment by lfdebrux** [comment]
@samuelhwilliams I guess that would also delete the index for g-cloud-10? Ideally there would be the ability for multiple search indexes in `settings.yml`.

**Comment by samuelhwilliams** [comment]
That ability exists. `settings.yml:index.indices` is just a list of indices to create. You can add just add a new entry to the list to also index g-cloud-9, e.g. below:

```
index:
  repository: digitalmarketplace-scripts
  command: venv/bin/python scripts/index-to-search-service.py
  test: http://localhost:9200/{index}

  dependencies:
    - digitalmarketplace-api
    - digitalmarketplace-search-api

  indices:
    - positional:
        - services
        - dev
      keyword:
        frameworks: g-cloud-9
        index: g-cloud-9
        create-with-mapping: services

    - positional:
        - services
        - dev
      keyword:
        frameworks: g-cloud-10
        index: g-cloud-10
        create-with-mapping: services-g-cloud-10

    - positional:
        - briefs
        - dev
      keyword:
        frameworks: digital-outcomes-and-specialists-2
        index: briefs-digital-outcomes-and-specialists
        create-with-mapping: briefs-digital-outcomes-and-specialists-2
```

Note: the `services` mapping in digitalmarketplace-search-api may actually be for g-cloud-10, so may break. But that's down to the search-api if it does, not the dmrunner.

**Pull request merged**
